# Generated by Django 5.1.2 on 2024-11-19 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('monto', models.DecimalField(decimal_places=65535, max_digits=65535)),
                ('fecha', models.DateTimeField()),
                ('tipo', models.TextField()),
            ],
            options={
                'db_table': 'transaccion',
                'managed': False,
            },
        ),
    ]
