# Generated by Django 5.1.2 on 2024-12-13 03:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0002_initial'),
        ('transacciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccion',
            name='tipo',
            field=models.CharField(choices=[('ingreso', 'Ingreso'), ('transferencia', 'Transferencia')], default='transferencia', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='emisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transacciones_emitidas', to='cuentas.cuenta'),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='motivo',
            field=models.CharField(blank=True, default='Sin motivo', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='receptor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transacciones_recibidas', to='cuentas.cuenta'),
        ),
    ]
